# Generated by Django 4.2.7 on 2023-11-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="modified on"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Info", "Info"),
                            ("Warning", "Warning"),
                            ("Danger", "Danger"),
                            ("Success", "Success"),
                        ],
                        default="Info",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="modified on"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="name")),
                ("owner", models.CharField(max_length=500, verbose_name="owner")),
                ("url", models.URLField(verbose_name="url")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "history",
                "verbose_name_plural": "histories",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="modified on"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="name")),
                (
                    "avatar_url",
                    models.URLField(max_length=500, verbose_name="avatar_url"),
                ),
                ("owner", models.CharField(max_length=500, verbose_name="owner")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="zips/",
                        verbose_name="file",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        editable=False,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="users",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository",
                "verbose_name_plural": "repositories",
                "unique_together": {("name", "owner")},
            },
        ),
    ]
