# Generated by Django 4.2.7 on 2023-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='avatar_url'),
        ),
    ]
