version: "3.9"

name: ghmrc

services:
    memcached:
        restart: unless-stopped
        image: memcached:alpine
        ports:
            - 11211:11211
        env_file: .env.docker
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "11211"]
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        restart: unless-stopped
        image: redis:alpine
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        env_file: .env.docker
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

    db:
        restart: unless-stopped
        image: postgres:14-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: .env.docker
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 3

    nginx:
        restart: unless-stopped
        build: .docker/nginx
        expose:
            - 80
            - 443
        ports:
            - 7080:80
            - 7443:443
        env_file: .env.docker
        depends_on:
            - django
            - nextjs

    nextjs:
        build:
            context: nextjs
            dockerfile: .docker/nextjs.Dockerfile
        ports:
            - 3000:3000
        env_file: .env.docker
        volumes:
            - nextjs:/home/app

    django:
        build:
            context: django
            dockerfile: .docker/django.Dockerfile
        ports:
            - 8000:8000 # django
            - 8001:8001 # flower
        env_file: .env.docker
        volumes:
            - django:/home/app
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
            memcached:
                condition: service_healthy

volumes:
    redis_data:
    postgres_data:
    pgadmin_data:
    django:
    nextjs:
