# Generated by Django 4.2.7 on 2023-11-26 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'suppor',
                'verbose_name_plural': 'support',
            },
        ),
    ]
