name: deploy
run-name: ${{ github.actor }} is running GHMRC CI/CD 🚀

on:
    push:
        branches:
            - $default-branch
    pull_request:
        branches:
            - $default-branch
    workflow_dispatch:

jobs:
    ci-django:
        uses: ./.github/django.yaml@master
        secrets: inherit

    ci-next:
        uses: ./.github/next.yaml@master
        secrets: inherit

    cd:
        needs:
            - ci-django
            - ci-next
        if: |
            always()
            && contains(needs.*.result, 'success')
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Set up Docker Compose
              run: |
                  sudo apt-get -y update
                  sudo apt-get -y install docker-ce docker-ce-cli containerd.io
                  sudo docker compose -f compose.yml build

            - name: Push to Docker Hub
              if: ${{ !github.event.act }}
              run: sudo docker compose -f compose.yml push
              env:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
